apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "crypto-tracker-core"
  namespace: "default"
  labels:
    app: "crypto-tracker-core"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "crypto-tracker-core"
  template:
    metadata:
      labels:
        app: "crypto-tracker-core"
    spec:
      containers:
      - name: "core-sha256-1"
        image: "us.gcr.io/crypto-tracker-2020/core:latest"
        env:
        - name: PORT
          value: "8080"
        envFrom:
        - secretRef:
            name: "crypto-tracker-secret"
        resources:
          requests:
            memory: "512Mi"
            cpu: "1"
          limits:
            memory: "512Mi"
            cpu: "1"
        readinessProbe:
          httpGet:
            path: /health/status
            port: 8080
        livenessProbe:
          httpGet:
            path: /health/status
            port: 8080
