apiVersion: v1
kind: Service
metadata:
  name: "crypto-tracker-core"
spec:
  type: NodePort
  ports:
    - targetPort: 8080
      port: 8080
      nodePort: 30008
  selector:
    app: "crypto-tracker-core"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "crypto-tracker-core"
  namespace: "default"
  labels:
    app: "crypto-tracker-core"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "crypto-tracker-core"
  template:
    metadata:
      labels:
        app: "crypto-tracker-core"
    spec:
      containers:
      - name: "core"
        image: "us.gcr.io/crypto-tracker-2020/core:latest"
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        envFrom:
        - secretRef:
            name: "crypto-tracker-secret"
        resources:
          requests:
            memory: "384Mi"
            cpu: "0.25"
          limits:
            memory: "384Mi"
            cpu: "0.25"
        readinessProbe:
          httpGet:
            path: /health/status
            port: 8080
          periodSeconds: 60
        livenessProbe:
          httpGet:
            path: /health/status
            port: 8080
          periodSeconds: 60
