name: Build pipeline

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.15
      - name: Run unit tests
        run: sbt clean test

  deploy:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - id: deploy
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.15
      - name: Build Docker image
        run: sbt docker:publishLocal
      - uses: google-github-actions/deploy-cloudrun@main
        with:
          image: us.gcr.io/crypto-tracker-2020/core
          service: crypto-tracker-core
          credentials: ${{ secrets.GCP_CREDENTIALS }}
