name: Deploy to GCP Cloud Run
on: [workflow_dispatch]

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: crypto-tracker-2020
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          export_default_credentials: true  # Set to true to authenticate the Cloud Run action

      - name: Authorize Docker push
        run: gcloud auth configure-docker

      - uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.15
      - name: Build and Push Docker image
        run: sbt docker:publish

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@main
        with:
          service: crypto-tracker-core
          image: us.gcr.io/crypto-tracker-2020/core:latest
          region: us-central1
          env_vars: MONGO_USER=${{secrets.MONGO_USER}},MONGO_PASSWORD=${{secrets.MONGO_PASSWORD}},MONGO_HOST=${{secrets.MONGO_HOST}}

      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
