name: Build pipeline

on:
  push:
    branches:
      - master

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.15
      - name: Run unit tests
        run: sbt clean test

  build-image:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: crypto-tracker-2020
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          export_default_credentials: true

      - name: Authorize Docker push
        run: gcloud auth configure-docker

      - uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.15
      - name: Build and Push Docker image
        run: sbt docker:publish